import express from "express";
import mongoose from "mongoose";
import BulkOrder from "../models/BulkOrder.js";
import { sampleBulkOrders } from "../data/bulkOrders.js";
import { authenticateToken } from "../middleware/auth.js";

const router = express.Router();

// 1. Submit New Bulk Order Request (Customer or Guest)
router.post("/", async (req, res) => {
  const {
    customerName,
    customerPhone,
    customerEmail,
    eventType,
    eventDate,
    eventTime,
    headCount,
    branchId,
    branchName,
    items,
    customizationRequirements,
    deliveryOption,
    deliveryAddress,
    additionalInstructions
  } = req.body;

  if (!customerName || !customerPhone || !items || items.length === 0) {
    return res.status(400).json({ error: "Customer name, phone, and at least one item are required" });
  }

  const orderId = `BLK-${Date.now().toString().slice(-6)}`;
  const estimatedCost = items.reduce((sum, i) => sum + (i.lineTotal || i.unitPrice * i.quantity || 0), 0);
  const defaultDiscount = headCount >= 100 ? 15 : headCount >= 50 ? 10 : 5;
  const finalQuotationAmount = Math.round(estimatedCost * (1 - defaultDiscount / 100));

  const newOrder = {
    orderId,
    customerName,
    customerPhone,
    customerEmail: customerEmail || "guest@bakesphere.com",
    eventType: eventType || "Birthday Party",
    eventDate: eventDate || new Date().toISOString().split("T")[0],
    eventTime: eventTime || "04:00 PM",
    headCount: Number(headCount) || 50,
    branchId: branchId || "BR-01",
    branchName: branchName || "Heritage Main Bakery (T. Nagar)",
    items,
    customizationRequirements: customizationRequirements || "",
    deliveryOption: deliveryOption || "delivery",
    deliveryAddress: deliveryAddress || "",
    additionalInstructions: additionalInstructions || "",
    status: "submitted",
    estimatedCost,
    discountPercent: defaultDiscount,
    finalQuotationAmount,
    managerNotes: "",
    paymentStatus: "pending",
    createdAt: new Date()
  };

  if (mongoose.connection.readyState === 1) {
    try {
      await BulkOrder.create(newOrder);
    } catch (e) {
      console.warn("MongoDB bulk order create error:", e.message);
    }
  }

  sampleBulkOrders.unshift(newOrder);

  res.status(201).json({
    message: `Bulk order inquiry '${orderId}' received successfully! Our catering manager will provide a tailored quote within 2 hours.`,
    order: newOrder
  });
});

// 2. GET /api/bulk-orders - List bulk orders (Filtered by branch / status)
router.get("/", async (req, res) => {
  const { branchId, status, search } = req.query;

  let results = [];
  if (mongoose.connection.readyState === 1) {
    try {
      const dbOrders = await BulkOrder.find({}).sort({ createdAt: -1 }).lean();
      if (dbOrders && dbOrders.length > 0) {
        results = dbOrders;
      } else {
        results = [...sampleBulkOrders];
      }
    } catch {
      results = [...sampleBulkOrders];
    }
  } else {
    results = [...sampleBulkOrders];
  }

  if (branchId && branchId !== "all") {
    results = results.filter((o) => o.branchId === branchId);
  }

  if (status && status !== "all") {
    results = results.filter((o) => o.status === status);
  }

  if (search) {
    const q = search.toLowerCase();
    results = results.filter(
      (o) =>
        o.orderId.toLowerCase().includes(q) ||
        o.customerName.toLowerCase().includes(q) ||
        o.customerPhone.includes(q) ||
        o.eventType.toLowerCase().includes(q)
    );
  }

  res.json({
    count: results.length,
    orders: results
  });
});

// 3. GET /api/bulk-orders/:id - Get single bulk order
router.get("/:id", async (req, res) => {
  const { id } = req.params;

  let order = null;
  if (mongoose.connection.readyState === 1) {
    try {
      order = await BulkOrder.findOne({ orderId: id }).lean();
    } catch {
      // fallback
    }
  }

  if (!order) {
    order = sampleBulkOrders.find((o) => o.orderId === id);
  }

  if (!order) {
    return res.status(404).json({ error: "Bulk order not found" });
  }

  res.json(order);
});

// 4. PUT /api/bulk-orders/:id/quote - Manager / Admin quotation & discount
router.put("/:id/quote", async (req, res) => {
  const { id } = req.params;
  const { discountPercent, finalQuotationAmount, managerNotes, items } = req.body;

  let updates = {
    status: "quoted",
    managerNotes: managerNotes || "Quotation generated by Branch Catering Desk."
  };

  if (discountPercent !== undefined) updates.discountPercent = Number(discountPercent);
  if (finalQuotationAmount !== undefined) updates.finalQuotationAmount = Number(finalQuotationAmount);
  if (items && Array.isArray(items)) {
    updates.items = items;
    updates.estimatedCost = items.reduce((sum, i) => sum + (i.lineTotal || i.unitPrice * i.quantity || 0), 0);
  }

  let order = null;
  if (mongoose.connection.readyState === 1) {
    try {
      order = await BulkOrder.findOneAndUpdate({ orderId: id }, { $set: updates }, { new: true }).lean();
    } catch {
      // fallback
    }
  }

  const idx = sampleBulkOrders.findIndex((o) => o.orderId === id);
  if (idx > -1) {
    sampleBulkOrders[idx] = { ...sampleBulkOrders[idx], ...updates };
    if (!order) order = sampleBulkOrders[idx];
  }

  if (!order) {
    return res.status(404).json({ error: "Bulk order not found" });
  }

  res.json({
    message: `Quotation updated for Bulk Order '${id}'. Customer has been notified.`,
    order
  });
});

// 5. PATCH /api/bulk-orders/:id/status - Update preparation & fulfillment status
router.patch("/:id/status", async (req, res) => {
  const { id } = req.params;
  const { status, paymentStatus, managerNotes } = req.body;

  let updates = {};
  if (status) updates.status = status;
  if (paymentStatus) updates.paymentStatus = paymentStatus;
  if (managerNotes) updates.managerNotes = managerNotes;

  let order = null;
  if (mongoose.connection.readyState === 1) {
    try {
      order = await BulkOrder.findOneAndUpdate({ orderId: id }, { $set: updates }, { new: true }).lean();
    } catch {
      // fallback
    }
  }

  const idx = sampleBulkOrders.findIndex((o) => o.orderId === id);
  if (idx > -1) {
    sampleBulkOrders[idx] = { ...sampleBulkOrders[idx], ...updates };
    if (!order) order = sampleBulkOrders[idx];
  }

  if (!order) {
    return res.status(404).json({ error: "Bulk order not found" });
  }

  res.json({
    message: `Bulk order '${id}' status changed to '${status || order.status}'.`,
    order
  });
});

export default router;
